# Generated by Django 6.0 on 2026-03-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Peito'), ('back', 'Costas'), ('legs', 'Pernas'), ('shoulders', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('abs', 'Abdômen')], max_length=20)),
                ('difficulty', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermediário'), (3, 'Avançado')], default=1)),
                ('description', models.TextField(blank=True, help_text='Breve descrição de como executar.')),
                ('video_url', models.URLField(blank=True, help_text='Link para um vídeo demonstrativo do exercício.', null=True)),
            ],
        ),
    ]
