# Generated by Django 6.0 on 2026-03-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercicios',
            new_name='Exercicio',
        ),
        migrations.AlterModelOptions(
            name='exercicio',
            options={'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
    ]
