# Generated by Django 6.0 on 2026-03-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutengine', '0002_rename_exercicios_exercicio_alter_exercicio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='muscle_group',
            field=models.CharField(choices=[('ches_upper', 'Peito (Superior)'), ('chest_lower', 'Peito (Inferior)'), ('chest_middle', 'Peito (Médio)'), ('back_upper', 'Costas (Parte Superior)'), ('back_lats', 'Costas (Grande Dorsal)'), ('back_middle', 'Costas (Miolo)'), ('back_lower', 'Costas (Parte Inferior)'), ('legs_quads', 'Pernas (Quadríceps)'), ('legs_hamstrings', 'Pernas (Posterior)'), ('legs_glutes', 'Pernas (Glúteos)'), ('legs_calves', 'Pernas (Panturrilhas)'), ('shoulders_ant', 'Ombros (Anterior)'), ('shoulders_med', 'Ombros (Médio)'), ('shoulders_post', 'Ombros (Posterior)'), ('biceps_long', 'Bíceps (Cabeça Longa)'), ('biceps_short', 'Bíceps (Cabeça Curta)'), ('triceps_long', 'Tríceps (Cabeça Longa)'), ('triceps_middle', 'Tríceps (Cabeça Medial)'), ('triceps_lat', 'Tríceps (Cabeça Lateral)'), ('abs', 'Abdômen')], max_length=20),
        ),
    ]
